export default {
  pages: [
    "pages/index/index",
    "pages/user/user",
    "pages/login/login",
    "pages/setting/setting",
    "pages/userinfo/userinfo",
    "pages/orders/orders",
    "pages/orderinfo/orderinfo",
    "pages/pay/pay",
    "pages/mynft/mynft",
    "pages/verify/verify",
    "pages/safty/safty",
    "pages/detail/detail",
    "pages/bindphone/bindphone",
    "pages/social/social",
    "pages/regrule/regrule",
    "pages/privacy/privacy",
    "pages/logoff/logoff",
    "pages/nftinfo/nftinfo",
    "pages/about/about",
    "pages/chain/chain",
    "pages/send/send",
    "pages/translog/translog",
    "pages/market/market",
    "pages/item/item",
    "pages/reg/reg",
    "pages/repass/repass",
    "pages/box/box",
    "pages/mybox/mybox",
    "pages/poster/poster",
    "pages/notice/notice",
    "pages/noticeinfo/noticeinfo",
    "pages/referlog/referlog",
    "pages/qpcard/qpcard",
    "pages/build/build",
    "pages/balance/balance",
    "pages/payconfig/payconfig",
    "pages/combolist/combolist",
    "pages/combo/combo",
    "pages/rank/rank",
    "pages/samenft/samenft",
    "pages/cashlog/cashlog",
    "pages/chaincreate/chaincreate",
    "pages/safepass/safepass",
  ],
  window: {
    backgroundTextStyle: "dark",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "墩墩艺术",
    navigationBarTextStyle: "white",
    backgroundColor: "#1c2236",
  },
};
